export const siteBrand={seriesName:'SysAdmin Lab',siteName:'Компьютерные сети: топологии, адресация и протоколы',shortSiteName:'Компьютерные сети',subtitle:'Интерактивные тренажёры по построению, настройке и диагностике базовых компьютерных сетей',description:'Учебный сайт по сетевым моделям, Ethernet, IPv4, маршрутизации, TCP, UDP, DHCP, DNS, NAT и диагностике компьютерных сетей',language:'ru'} as const;
export type SectionStatus='planned'|'available'|'inProgress';
export interface LearningSection{id:string;order:number;title:string;shortTitle:string;description:string;route:string;status:SectionStatus;theoryHours:number;practiceHours:number;topics:string[];expectedResult:string;futureFeatures:string[]}
const raw=[
['network-architecture',1,'Сетевая архитектура и модели','Архитектура и модели','Устройство компьютерной сети, роли узлов и сетевых устройств, модели OSI и TCP/IP, инкапсуляция и путь данных.',['Компьютерная сеть','Клиент и сервер','OSI и TCP/IP','Инкапсуляция']],
['physical',2,'Физическое подключение и диагностика','Физическое подключение','Среды передачи, кабели, разъёмы, интерфейсы и поиск неисправностей физического уровня.',['Медь и оптика','Витая пара','Интерфейсы','Диагностика линии']],
['ethernet',3,'Ethernet и коммутация','Ethernet и коммутация','Кадры Ethernet, MAC-адреса, работа коммутатора и широковещательные домены.',['Кадр Ethernet','MAC-адрес','Таблица коммутации','VLAN']],
['ipv4-arp-icmp',4,'IPv4, ARP и ICMP','IPv4, ARP и ICMP','Доставка пакета IPv4, разрешение адресов ARP и служебные сообщения ICMP.',['Пакет IPv4','ARP','ICMP','ping']],
['subnetting',5,'IPv4-адресация и подсети','IPv4 и подсети','Адрес сети, узла и broadcast, маски, префиксы и базовое проектирование подсетей.',['IPv4-адрес','Маска','Префикс CIDR','Подсети']],
['routing',6,'Маршрутизация и выбор пути','Маршрутизация','Шлюз по умолчанию, таблица маршрутизации, метрика и выбор следующего узла.',['Шлюз','Маршрут','Метрика','Выбор пути']],
['transport',7,'TCP, UDP и сетевые порты','TCP, UDP и порты','Транспортный уровень, номера портов, надёжная и дейтаграммная доставка.',['TCP','UDP','Порты','Сокеты']],
['services',8,'DHCP, DNS и NAT','DHCP, DNS и NAT','Автоматическая настройка узлов, разрешение имён и трансляция сетевых адресов.',['DHCP','DNS','NAT','PAT']],
['constructor',9,'Конструктор и диагностика сети','Конструктор сети','Итоговое проектирование простой сети и системный поиск причин потери связности.',['Топология','План адресации','Проверка связности','Диагностика']]
] as const;
export const sections:LearningSection[]=raw.map(([id,order,title,shortTitle,description,topics])=>({id,order,title,shortTitle,description,route:`/sections/${id}`,status:id==='network-architecture'?'available':'planned',theoryHours:2,practiceHours:4,topics:[...topics],expectedResult:`Объяснять ключевые принципы темы «${shortTitle}» и применять их при проектировании и диагностике сети.`,futureFeatures:['Теория','Интерактивная модель','Практические задания','Диагностика','Контрольный режим','Статистика раздела']}));
export type LearningItemType='overview'|'theory'|'simulator'|'practice'|'diagnostics'|'control'|'statistics';
export interface SectionNavigationItem{id:string;sectionId:string;title:string;route:string;type:LearningItemType;order:number;status:'available'|'planned'|'disabled';includeInSequence:boolean}
const architectureItems:[string,string,LearningItemType][]=[['overview','Обзор','overview'],['theory','Теория','theory'],['devices','Узлы и сетевые устройства','simulator'],['network-types','Типы сетей и топологии','practice'],['osi','Модель OSI','simulator'],['tcp-ip','Модель TCP/IP','simulator'],['model-mapping','OSI и TCP/IP','practice'],['encapsulation','Инкапсуляция данных','simulator'],['data-path','Путь данных','simulator'],['network-diagram','Разбор схемы сети','practice'],['layer-diagnostics','Диагностика по уровням','diagnostics'],['find-error','Найди ошибку','diagnostics'],['control','Контрольный режим','control'],['statistics','Статистика раздела','statistics']];
export const sectionNavigation:Record<string,SectionNavigationItem[]>=Object.fromEntries(sections.map(s=>[s.id,s.id==='network-architecture'?architectureItems.map(([slug,title,type],i)=>({id:`${s.id}-${slug}`,sectionId:s.id,title,route:i===0?s.route:`${s.route}/${slug}`,type,order:i+1,status:'available' as const,includeInSequence:true})):[{id:`${s.id}-overview`,sectionId:s.id,title:'Обзор',route:s.route,type:'overview',order:1,status:'available',includeInSequence:true},...s.futureFeatures.slice(0,-1).map((title,i)=>({id:`${s.id}-future-${i}`,sectionId:s.id,title,route:s.route,type:'theory' as LearningItemType,order:i+2,status:'planned' as const,includeInSequence:false}))]]));
export const getSection=(id:string)=>sections.find(s=>s.id===id);
export const getNeighbors=(id:string)=>{const i=sections.findIndex(s=>s.id===id);return{previous:i>0?sections[i-1]:undefined,next:i>=0&&i<sections.length-1?sections[i+1]:undefined}};
export const getLearningItem=(sectionId:string,slug='overview')=>sectionNavigation[sectionId]?.find((x,i)=>i===0?slug==='overview':x.route.endsWith(`/${slug}`));
