import './style.css';
import {getNeighbors,getSection,sectionNavigation,sections,siteBrand} from './config';
import {applyTheme,getTheme,loadProgress,resetProgress,setTheme,visit,type Theme} from './storage';
import {architecturePage,bindArchitecture} from './architecturePages';

const app=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(name:string)=>`<span class="icon" aria-hidden="true">${name}</span>`;
const status=(value='planned')=>`<span class="status ${value}"><i></i> ${value==='available'?'Доступен':'Запланировано'}</span>`;
const card=(s:typeof sections[number])=>`<article class="section-card"><div class="card-top"><span class="number">${String(s.order).padStart(2,'0')}</span>${status(s.status)}</div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p><div class="chips">${s.topics.slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div><a class="text-link" href="${s.route}" data-link>Открыть обзор ${icon('↗')}</a></article>`;
const shell=(content:string)=>`<header><a class="brand" href="/" data-link><span class="brand-mark">S</span><span><b>${siteBrand.seriesName}</b><small>${siteBrand.shortSiteName}</small></span></a><nav aria-label="Главная навигация"><a href="/" data-link>Главная</a><a href="/sections" data-link>Разделы</a><a href="/statistics" data-link>Статистика</a></nav><div class="header-actions"><button class="theme-btn" aria-label="Сменить тему" title="Сменить тему">◐</button><button class="menu-btn" aria-label="Открыть меню" aria-expanded="false">☰</button></div></header><main id="main" tabindex="-1">${content}</main><footer><div class="brand-footer"><b>${siteBrand.seriesName}</b><span>Практика. Понимание. Система.</span></div><p>${siteBrand.shortSiteName} · 54 часа · 9 учебных разделов</p><p>© 2026 Учебный проект</p></footer>`;
const metrics=`<div class="metrics"><div><b>54</b><span>часа обучения</span></div><div><b>18</b><span>часов теории</span></div><div><b>36</b><span>часов практики</span></div><div><b>9</b><span>лабораторных</span></div></div>`;

function home(){const p=loadProgress();return `<section class="hero"><div class="eyebrow"><span></span> Учебный трек · IT-инфраструктура</div><h1>Компьютерные сети:<br><em>от кабеля до протокола</em></h1><p>${siteBrand.subtitle}. Освойте логику сети шаг за шагом.</p><div class="hero-actions"><a class="button primary" href="${p.visited.length?p.lastRoute:'/sections/architecture'}" data-link>${icon('▶')} ${p.visited.length?'Продолжить обучение':'Начать обучение'}</a><a class="button secondary" href="/sections" data-link>Смотреть программу ${icon('→')}</a></div>${metrics}<div class="network-art" aria-hidden="true"><div class="ring r1"></div><div class="ring r2"></div><div class="hub">NET</div>${['PC','SW','RTR','SRV'].map((x,i)=>`<div class="node n${i+1}">${x}</div>`).join('')}</div></section><section class="outcome"><div><div class="eyebrow"><span></span> Результат обучения</div><h2>Видеть сеть как<br><em>единую систему</em></h2></div><p>Вы научитесь понимать путь данных, проектировать адресацию и последовательно находить причины сетевых сбоев — от физического уровня до прикладных сервисов.</p></section><section class="featured"><div class="section-heading"><div><span class="kicker">Учебная программа</span><h2>9 разделов. Один маршрут.</h2></div><a href="/sections" data-link>Вся программа →</a></div><div class="card-grid">${sections.slice(0,3).map(card).join('')}</div></section>`}
function sectionsPage(){return `<section class="page-head"><div class="breadcrumbs"><a href="/" data-link>Главная</a><span>/</span><span>Учебные разделы</span></div><span class="kicker">Учебная программа</span><h1>От архитектуры<br>до диагностики</h1><p>Последовательный маршрут из девяти разделов. Каждый следующий шаг опирается на предыдущий.</p>${metrics}</section><section class="catalog"><div class="catalog-title"><b>01—09</b><span>Все разделы пока находятся на этапе подготовки</span></div><div class="card-grid">${sections.map(card).join('')}</div></section>`}
function sectionPage(id:string){const s=getSection(id);if(!s)return notFound();visit(id,location.pathname);const n=getNeighbors(id);const items=sectionNavigation[id];return `<section class="section-hero"><div class="breadcrumbs"><a href="/" data-link>Главная</a><span>/</span><a href="/sections" data-link>Разделы</a><span>/</span><span>${String(s.order).padStart(2,'0')}</span></div><div class="section-index">Раздел ${String(s.order).padStart(2,'0')} <span>из 09</span></div><h1>${esc(s.title)}</h1><p>${esc(s.description)}</p><div class="progress-label"><span>Прогресс раздела</span><b>0%</b></div><div class="progress" role="progressbar" aria-label="Прогресс раздела: 0 процентов" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i></i></div></section><section class="section-layout"><aside><b>Содержание раздела</b>${items.map((x,i)=>`<div class="toc ${x.status==='available'?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><span>${esc(x.title)}</span>${x.status==='planned'?'<small>Скоро</small>':''}</div>`).join('')}</aside><div class="overview"><div class="notice"><span>В разработке</span><h2>Раздел готовится к запуску</h2><p>Материалы, тренажёры и задания появятся здесь по мере готовности.</p></div><h2>Что вы изучите</h2><div class="topic-grid">${s.topics.map((t,i)=>`<div><span>0${i+1}</span><b>${esc(t)}</b></div>`).join('')}</div><div class="expected"><span>После раздела вы сможете</span><p>${esc(s.expectedResult)}</p></div></div></section><nav class="prev-next" aria-label="Между разделами">${n.previous?`<a href="${n.previous.route}" data-link><small>← Предыдущий раздел</small><b>${esc(n.previous.shortTitle)}</b></a>`:'<span></span>'}<a class="all" href="/sections" data-link>Все разделы</a>${n.next?`<a class="next" href="${n.next.route}" data-link><small>Следующий раздел →</small><b>${esc(n.next.shortTitle)}</b></a>`:`<a class="next" href="/statistics" data-link><small>Завершить маршрут →</small><b>Общая статистика</b></a>`}</nav>`}
function stats(){const p=loadProgress();const percent=Math.round(p.completed.length/sections.length*100);return `<section class="page-head stats-head"><div class="breadcrumbs"><a href="/" data-link>Главная</a><span>/</span><span>Статистика</span></div><span class="kicker">Ваш прогресс</span><h1>Двигайтесь<br>в своём темпе</h1><p>Прогресс хранится только на этом устройстве. Никаких аккаунтов и передачи данных.</p></section><section class="stats-grid"><div class="score"><div class="score-ring" style="--p:${percent}"><b>${percent}%</b><span>завершено</span></div></div><div class="stat"><b>${p.visited.length}</b><span>разделов посещено</span></div><div class="stat"><b>${p.completed.length}</b><span>разделов завершено</span></div><div class="stat"><b>${sections.length-p.completed.length}</b><span>разделов впереди</span></div></section><section class="empty-state"><span>${icon('⌁')}</span><h2>${p.visited.length?'Обучение начато':'Здесь появятся результаты'}</h2><p>${p.visited.length?'Продолжайте с последнего посещённого раздела.':'Откройте первый раздел, и мы сохраним ваш учебный маршрут.'}</p><a class="button primary" href="${p.lastRoute}" data-link>${p.visited.length?'Продолжить обучение':'Начать обучение'} →</a><button class="reset">Сбросить прогресс</button></section>`}
function notFound(){return `<section class="not-found"><b>404</b><span>Маршрут не найден</span><h1>Пакет потерялся<br>по дороге</h1><p>Такого адреса нет в нашей таблице маршрутизации.</p><a class="button primary" href="/" data-link>← Вернуться на главную</a></section>`}
function render(){const path=location.pathname.replace(/\/$/,'')||'/';let view=path==='/'?home():path==='/sections'?sectionsPage():path==='/statistics'?stats():path.startsWith('/sections/')?sectionPage(path.split('/')[2]):notFound();app.innerHTML=shell(view);document.title=`${path==='/'?siteBrand.siteName:path==='/sections'?'Учебные разделы':path==='/statistics'?'Статистика':getSection(path.split('/')[2])?.title||'Страница не найдена'} — ${siteBrand.seriesName}`;bind();scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>document.querySelector<HTMLElement>('#main')?.focus({preventScroll:true}))}
function navigate(path:string){history.pushState({},'',path);render()}
function bind(){document.querySelectorAll<HTMLAnchorElement>('[data-link]').forEach(a=>a.onclick=e=>{e.preventDefault();navigate(a.pathname)});document.querySelector('.menu-btn')?.addEventListener('click',e=>{const b=e.currentTarget as HTMLButtonElement;document.querySelector('header nav')?.classList.toggle('open');b.setAttribute('aria-expanded',String(b.getAttribute('aria-expanded')!=='true'))});document.querySelector('.theme-btn')?.addEventListener('click',()=>{const order:Theme[]=['system','light','dark'];setTheme(order[(order.indexOf(getTheme())+1)%3])});document.querySelector('.reset')?.addEventListener('click',()=>{resetProgress();render()})}
applyTheme();addEventListener('popstate',render);render();
