import {sectionNavigation} from './config';
import {chooseMedium,diagnosePhysical,linkQuality,media,type LinkSymptom} from './physicalNetwork';
import {completeStep,loadSectionProgress,recordAnswer,recordAttempt,visitStep} from './storage';

const SID='physical';const items=sectionNavigation[SID];
const cards=(xs:[string,string][])=>`<div class="lesson-cards">${xs.map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`;
const quiz=(id:string,question:string,answers:string[],correct:number,topic:string)=>`<section class="quiz" data-physical-quiz data-correct="${correct}" data-topic="${topic}"><h2>Проверьте себя</h2><p>${question}</p><div class="answers">${answers.map((answer,index)=>`<label><input type="radio" name="${id}" value="${index}"><span>${answer}</span></label>`).join('')}</div><button class="button primary check-physical-answer" type="button">Проверить</button><div class="feedback" role="status" aria-live="polite"></div></section>`;

function overview(){const p=loadSectionProgress(SID);const next=items.find(x=>!p.completed.includes(x.id))||items.at(-1)!;return `<div class="overview-grid"><section><span class="kicker">Раздел 02 · Доступен</span><h2>От сигнала до стабильного соединения</h2><p class="lead">Научитесь выбирать среду передачи, проверять кабельную линию и системно находить неисправности физического уровня.</p><div class="lesson-metrics"><span><b>2 ч</b> теория</span><span><b>4 ч</b> практика</span><span><b>${p.completed.length}/13</b> завершено</span></div><a class="button primary" href="${next.route}" data-link>${p.visited.length>1?'Продолжить обучение':'Начать: Физический уровень'} →</a></section><div class="physical-hero-lab" aria-label="Последовательность проверки физического подключения"><span>Питание</span><i>→</i><span>Порт и интерфейс</span><i>→</i><span>Кабель и разъёмы</span><i>→</i><span>Сигнал и согласование</span></div></div>${cards([['Среды передачи','Медь, оптика и радиоканал: возможности и ограничения.'],['Витая пара','Категории кабеля, пары, длина линии и защита от помех.'],['Разъёмы','8P8C, LC, SC и аккуратная коммутация.'],['Интерфейсы','NIC, SFP, скорость, duplex и автосогласование.'],['Индикаторы','Link и Activity как первые источники диагностических данных.'],['Выбор кабеля','Подбор среды по расстоянию, помехам и мобильности.'],['Качество сигнала','Влияние длины, повреждений и силовых линий.'],['Диагностика','Порядок проверки от питания до конфигурации порта.'],['Контроль','Итоговая проверка с подробным разбором ошибок.']])}`}

function theory(){return `<section class="prose"><h2>Задача физического уровня</h2><p>Физический уровень передаёт отдельные биты в виде электрических, оптических или радиосигналов. Он определяет среду, разъёмы, уровни сигнала, скорость, синхронизацию и способ подключения интерфейсов.</p><h2>Линия связи как система</h2><p>Рабочая линия состоит не только из кабеля. В неё входят сетевые адаптеры, порты коммутатора, трансиверы, патч‑панели, розетки, патч‑корды и места оконцевания. Отказ любого элемента может погасить Link.</p>${cards([['Сигнал','Физическое представление битов в выбранной среде.'],['Полоса пропускания','Потенциальный объём данных, передаваемый за единицу времени.'],['Затухание','Ослабление сигнала с ростом расстояния и числа соединений.'],['Помехи','Воздействие соседних пар, радиосигналов и силового оборудования.'],['Link','Признак того, что интерфейсы обнаружили физическое соединение.'],['Duplex','Режим одновременной или попеременной передачи.']])}<h2>Безопасный порядок проверки</h2><p>Сначала проверьте питание и индикацию, затем посадку разъёмов и кабель. После этого исследуйте трансивер, скорость и duplex. Такой порядок быстрее и безопаснее случайной замены оборудования.</p></section>${quiz('physical-theory','Что подтверждает горящий индикатор Link?',['Приложение отвечает','Интерфейсы обнаружили физическое соединение','IP-адрес настроен правильно'],1,'основы')}`}

function mediaPage(){return `<section><h2>Сравнение сред передачи</h2><p>Нажмите на среду, чтобы увидеть её характеристики и подходящие сценарии.</p><div class="media-grid">${media.map(x=>`<button type="button" data-medium="${x.id}"><span>${x.id==='utp'?'⌁':x.id==='fiber'?'◉':')))'}</span><b>${x.name}</b><small>${x.distance}</small></button>`).join('')}</div><div id="medium-result" class="result-panel" role="status">Выберите среду передачи.</div><h2>Практическое правило</h2><p>Медь удобна на горизонтальных линиях до 100 метров. Оптика подходит для магистралей, больших расстояний и зон с сильными электромагнитными помехами. Радиоканал нужен мобильным клиентам, но разделяет эфир с соседями.</p></section>${quiz('media-q','Что лучше выбрать для связи зданий на расстоянии 350 метров?',['Витую пару','Оптоволокно','Короткий USB-кабель'],1,'среды')}`}

function twistedPair(){return `<section><h2>Витая пара</h2><p>Попарное скручивание проводников уменьшает взаимные и внешние помехи. Для Gigabit Ethernet обычно нужны все четыре пары и корректное оконцевание обеих сторон.</p><div class="comparison"><div><b>Cat 5e</b><p>Типовой выбор для 1 Гбит/с до 100 м при качественном монтаже.</p></div><div><b>Cat 6</b><p>Лучшие характеристики по помехам; 10 Гбит/с на ограниченной длине.</p></div><div><b>Cat 6A</b><p>Рассчитана на 10 Гбит/с до 100 м и требует аккуратного монтажа.</p></div></div><h2>U/UTP и экранирование</h2><p>Экран помогает только при правильном проектировании и заземлении. Неправильно смонтированный экран не компенсирует плохую трассу, чрезмерные перегибы или расплетение пар у коннектора.</p>${cards([['Постоянная линия','Кабель между патч‑панелью и розеткой.'],['Патч‑корд','Гибкое соединение устройства с розеткой или панелью.'],['Канал','Постоянная линия вместе с патч‑кордами и соединениями.']])}</section>${quiz('pair-q','Почему проводники скручены попарно?',['Для уменьшения помех','Чтобы увеличить массу кабеля','Для назначения IP-адреса'],0,'витая пара')}`}

function connectors(){return `<section><h2>Разъёмы и оконцевание</h2><div class="connector-board"><article><b>8P8C</b><span>Медные Ethernet-линии</span><small>Часто неформально называют RJ‑45</small></article><article><b>LC</b><span>Компактный оптический разъём</span><small>Распространён в SFP-модулях</small></article><article><b>SC</b><span>Оптический разъём push‑pull</span><small>Крупнее LC и удобен на панелях</small></article></div><h2>Распиновка T568B</h2><div class="pinout" aria-label="Цвета жил T568B">${['бело-оранжевый','оранжевый','бело-зелёный','синий','бело-синий','зелёный','бело-коричневый','коричневый'].map((x,i)=>`<span><b>${i+1}</b>${x}</span>`).join('')}</div><p>Для обычного прямого кабеля используйте один стандарт на обоих концах. Важнее сохранить пары и минимально расплетать их у контактов.</p></section>${quiz('connector-q','Какой разъём обычно установлен в SFP-модуле для двухволоконной оптики?',['LC','8P8C','BNC'],0,'разъёмы')}`}

function interfaces(){return `<section><h2>Сетевые интерфейсы</h2><p>Выберите элемент и изучите его роль в физическом соединении.</p><div class="interface-list"><button type="button" data-interface="nic">NIC</button><button type="button" data-interface="switch">Порт switch</button><button type="button" data-interface="sfp">SFP/SFP+</button><button type="button" data-interface="poe">PoE</button></div><div id="interface-result" class="result-panel" role="status">Выберите интерфейс.</div><h2>Автосогласование</h2><p>Два Ethernet-интерфейса обмениваются возможностями и выбирают общую скорость и duplex. Если линия работает медленнее ожидаемого, проверьте согласованную скорость, качество всех пар и ограничения оборудования.</p></section>${quiz('interface-q','Что делает SFP-модуль?',['Преобразует интерфейс в нужный тип физической среды','Назначает IP-адрес','Фильтрует DNS-запросы'],0,'интерфейсы')}`}

function indicators(){return `<section><h2>Индикаторы линии</h2><p>Выберите состояние порта и начните диагностику с наблюдаемого факта.</p><div class="indicator-panel"><button type="button" data-link-state="no-light"><i class="led off"></i>Не горит</button><button type="button" data-link-state="ok"><i class="led on"></i>Горит постоянно</button><button type="button" data-link-state="flapping"><i class="led blink"></i>Периодически гаснет</button><button type="button" data-link-state="slow"><i class="led amber"></i>Неожиданный цвет</button></div><div id="indicator-result" class="result-panel" role="status">Выберите состояние индикатора.</div><p class="note">Цвет и назначение индикаторов зависят от модели устройства — сверяйтесь с документацией. Сам факт отсутствия Link остаётся важным диагностическим признаком.</p></section>${quiz('indicator-q','Link не горит на обоих концах. Что проверить первым?',['DNS','Питание, разъёмы и кабель','Настройки браузера'],1,'индикация')}`}

function cableChoice(){return `<section><h2>Подберите среду</h2><p>Задайте условия линии. Тренажёр предложит базовый вариант и объяснит выбор.</p><form id="medium-form" class="medium-form"><label>Расстояние, м<input name="distance" type="number" min="1" max="10000" value="80"></label><label><input name="interference" type="checkbox"> Сильные электромагнитные помехи</label><label><input name="mobility" type="checkbox"> Клиенту нужна мобильность</label><button class="button primary" type="submit">Подобрать среду</button></form><div id="choice-result" class="result-panel" role="status">Укажите условия и нажмите «Подобрать среду».</div></section>${quiz('choice-q','Линия 70 м проходит рядом с мощным электродвигателем. Надёжный выбор?',['Неэкранированная медь без обследования','Оптоволокно','Телефонный кабель'],1,'выбор среды')}`}

function signalQuality(){return `<section><h2>Оценка качества медной линии</h2><p>Это учебная модель: она показывает направление влияния факторов, но не заменяет сертификационный тестер.</p><form id="quality-form" class="quality-form"><label>Длина: <b id="length-value">80 м</b><input name="length" type="range" min="10" max="130" value="80"></label><label>Повреждённых пар<select name="pairs"><option value="0">0</option><option value="1">1</option><option value="2">2</option></select></label><label><input name="power" type="checkbox"> Трасса рядом с силовым кабелем</label></form><div class="quality-meter"><i style="width:100%"></i></div><div id="quality-result" class="result-panel" role="status">100/100 · Стабильная линия</div><h2>Что измеряет тестер</h2>${cards([['Wiremap','Последовательность жил, обрывы, замыкания и перепутанные пары.'],['Длина','Расстояние до конца линии или места повреждения.'],['NEXT','Взаимное влияние сигналов соседних пар.'],['Затухание','Потеря мощности сигнала по длине линии.']])}</section>${quiz('quality-q','Что выявляет wiremap-тест?',['Обрывы и перепутанные жилы','Ошибку DNS','Неверный пароль Wi‑Fi'],0,'качество')}`}

function diagnosticAlgorithm(){return `<section><h2>Алгоритм физической диагностики</h2><div class="diagnostic-steps">${[['01','Зафиксируйте симптом','Нет Link, линия нестабильна или скорость ниже ожидаемой.'],['02','Проверьте питание','Устройство включено, адаптер и PoE работают.'],['03','Осмотрите соединение','Разъёмы посажены, нет повреждений и резких перегибов.'],['04','Замените простое','Используйте заведомо исправный короткий патч‑корд и другой порт.'],['05','Проверьте линию','Wiremap, длина, затухание и качество оконцевания.'],['06','Проверьте согласование','Скорость, duplex и совместимость трансиверов.'],['07','Зафиксируйте результат','Запишите причину, действие и итог повторной проверки.']].map(x=>`<article><b>${x[0]}</b><div><strong>${x[1]}</strong><p>${x[2]}</p></div></article>`).join('')}</div><div class="fault-card"><span>Важно</span><p>Не смотрите в торец подключённого оптического волокна. Для проверки используйте измеритель мощности и соблюдайте правила лазерной безопасности.</p></div></section>${quiz('algorithm-q','Зачем использовать заведомо исправный патч‑корд?',['Чтобы быстро исключить простой элемент линии','Чтобы изменить IP-сеть','Чтобы очистить таблицу MAC'],0,'алгоритм')}`}

function findFault(){return `<section><h2>Найдите неисправность</h2><p>Сценарий: рабочая станция вчера работала на 1 Гбит/с. После перестановки стола Link согласуется только на 100 Мбит/с. Кабель сильно зажат ножкой стола.</p><div class="fault-options"><button type="button" data-fault="dns">Перенастроить DNS</button><button type="button" data-fault="cable">Освободить кабель, осмотреть его и проверить все пары</button><button type="button" data-fault="browser">Переустановить браузер</button></div><div id="fault-result" class="result-panel" role="status">Выберите первое обоснованное действие.</div></section>`}

const controlQuestions=[['Что передаёт физический уровень?',['Маршруты','Биты в виде сигналов','Доменные имена'],1],['Максимальная стандартная длина медного Ethernet-канала?',['10 м','100 м','1 км'],1],['Какая среда устойчива к электромагнитным помехам?',['Оптоволокно','U/UTP','Радиоканал'],0],['Почему скручивают пары?',['Для снижения помех','Для питания сервера','Для назначения VLAN'],0],['Какой разъём характерен для медного Ethernet?',['LC','8P8C','SC'],1],['Что означает отсутствие Link?',['Физическое соединение не установлено','DNS точно неисправен','Приложение удалено'],0],['Что проверяет wiremap?',['Маршрут пакета','Жилы, обрывы и перепутанные пары','Имя пользователя'],1],['Что выбрать для линии 300 м?',['Оптоволокно','Патч-корд Cat 5e','USB'],0],['Скорость упала до 100 Мбит/с. Возможная причина?',['Повреждение одной из пар','Смена DNS','Ошибка браузера'],0],['С чего начинается диагностика без Link?',['С питания, портов и кабеля','С переустановки ОС','С настройки NAT'],0]] as const;
function control(){return `<section class="control"><h2>Контрольный режим</h2><p>10 заданий без подсказок. После завершения вы увидите результат, ошибки и правильные ответы.</p><form id="control-form">${controlQuestions.map((q,i)=>`<fieldset data-correct="${q[2]}"><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label><input type="radio" name="pcq${i}" value="${j}"> ${a}</label>`).join('')}</fieldset>`).join('')}<button class="button primary">Завершить попытку</button></form><div id="control-result" class="result-panel" role="status" aria-live="polite"></div></section>`}

function statistics(){const p=loadSectionProgress(SID),percent=Math.round(p.completed.length/items.length*100),next=items.find(x=>!p.completed.includes(x.id));return `<section><h2>Статистика раздела</h2><div class="stats-grid lesson-stats"><div class="score"><div class="score-ring" style="--p:${percent}"><b>${percent}%</b><span>завершено</span></div></div><div class="stat"><b>${p.completed.length}/13</b><span>материалов</span></div><div class="stat"><b>${p.answers?Math.round(p.correct/p.answers*100):0}%</b><span>точность</span></div><div class="stat"><b>${p.bestScore}%</b><span>лучший контроль</span></div></div><h2>Ошибки по темам</h2><div class="error-summary">${Object.keys(p.errors).length?Object.entries(p.errors).map(([topic,count])=>`<span>${topic}: <b>${count}</b></span>`).join(''):'Ошибок пока нет.'}</div>${next?`<a class="button primary" href="${next.route}" data-link>Продолжить: ${next.title} →</a>`:`<div class="completion"><h3>Раздел завершён</h3><p>Следующий раздел: Ethernet и коммутация</p><a class="button primary" href="/sections/ethernet" data-link>Перейти к следующему разделу →</a></div>`}</section>`}

const renderers:Record<string,()=>string>={overview,theory,media:mediaPage,'twisted-pair':twistedPair,connectors,interfaces,'link-indicators':indicators,'cable-choice':cableChoice,'signal-quality':signalQuality,'diagnostic-algorithm':diagnosticAlgorithm,'find-fault':findFault,control,statistics};
export function physicalPage(slug='overview'){const item=items.find((x,i)=>i===0?slug==='overview':x.route.endsWith(`/${slug}`));if(!item)return null;visitStep(SID,item.id,item.route);const p=loadSectionProgress(SID),index=items.indexOf(item),percent=Math.round(p.completed.length/items.length*100);return `<section class="lesson-head physical-head"><div class="breadcrumbs"><a href="/" data-link>Главная</a><span>/</span><a href="/sections" data-link>Разделы</a><span>/</span><a href="/sections/physical" data-link>Физическое подключение</a></div><button class="contents-toggle" aria-expanded="false">Содержание · ${index+1}/13</button><span class="kicker">Физическое подключение и диагностика</span><h1>${item.title}</h1><p>Шаг ${index+1} из 13 · ${percent}% завершено</p><div class="progress" role="progressbar" aria-label="Прогресс раздела: ${percent} процентов" aria-valuenow="${percent}" aria-valuemin="0" aria-valuemax="100"><i style="width:${percent}%"></i></div></section><div class="lesson-shell"><aside class="lesson-toc"><button class="toc-close" aria-label="Закрыть содержание">×</button><b>Содержание раздела</b>${items.map((x,i)=>`<a href="${x.route}" data-link class="toc ${x.id===item.id?'active':''}" ${x.id===item.id?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span><span>${x.title}</span><small>${p.completed.includes(x.id)?'✓':'○'}</small></a>`).join('')}</aside><article class="lesson-content physical-content">${renderers[slug]()}</article></div>${lessonNav(index,item.id)}`}
function lessonNav(index:number,id:string){const prev=items[index-1],next=items[index+1];return `<nav class="prev-next lesson-nav" aria-label="Между материалами">${prev?`<a href="${prev.route}" data-link><small>← Предыдущий материал</small><b>${prev.title}</b></a>`:`<a href="/sections/network-architecture/statistics" data-link><small>← Предыдущий раздел</small><b>Архитектура и модели</b></a>`}<a class="all" href="/sections/physical" data-link>К обзору раздела</a>${next?`<a class="next complete-next" data-complete-physical="${id}" href="${next.route}" data-link><small>Далее →</small><b>${next.title}</b></a>`:`<a class="next finish-section" data-complete-physical="${id}" href="/sections/physical/statistics" data-link><small>Завершить</small><b>Завершить раздел →</b></a>`}</nav>`}

export function bindPhysical(){
  document.querySelector('.contents-toggle')?.addEventListener('click',()=>document.querySelector('.lesson-toc')?.classList.add('open'));
  document.querySelector('.toc-close')?.addEventListener('click',()=>document.querySelector('.lesson-toc')?.classList.remove('open'));
  document.querySelectorAll<HTMLElement>('[data-complete-physical]').forEach(x=>x.addEventListener('click',()=>completeStep(SID,x.dataset.completePhysical!)));
  document.querySelectorAll<HTMLButtonElement>('[data-medium]').forEach(button=>button.onclick=()=>{const x=media.find(m=>m.id===button.dataset.medium)!;document.querySelector('#medium-result')!.innerHTML=`<b>${x.name}</b><p>${x.distance} · ${x.speed}</p><small>${x.immune?'Устойчива':'Чувствительна'} к электромагнитным помехам · Применение: ${x.use}</small>`});
  const interfaceInfo={nic:'Сетевой адаптер преобразует данные устройства в сигналы выбранной среды.',switch:'Порт коммутатора принимает линию, согласует режим и показывает состояние Link/Activity.',sfp:'Сменный трансивер задаёт тип оптики или меди, длину волны и поддерживаемую скорость.',poe:'Power over Ethernet передаёт питание и данные по одной медной линии совместимому устройству.'};
  document.querySelectorAll<HTMLButtonElement>('[data-interface]').forEach(button=>button.onclick=()=>document.querySelector('#interface-result')!.textContent=interfaceInfo[button.dataset.interface as keyof typeof interfaceInfo]);
  document.querySelectorAll<HTMLButtonElement>('[data-link-state]').forEach(button=>button.onclick=()=>{const d=diagnosePhysical(button.dataset.linkState as LinkSymptom);document.querySelector('#indicator-result')!.innerHTML=`<b>${d.cause}</b><p>${d.first}</p>`});
  document.querySelector<HTMLFormElement>('#medium-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget),distance=Number(data.get('distance')),id=chooseMedium(distance,data.has('interference'),data.has('mobility')),x=media.find(m=>m.id===id)!;document.querySelector('#choice-result')!.innerHTML=`<b>${x.name}</b><p>${data.has('mobility')?'Нужна мобильность.':distance>100?'Длина больше 100 м.':data.has('interference')?'Есть сильные помехи.':'Длина укладывается в медный канал до 100 м.'}</p><small>${x.use}</small>`;completeStep(SID,items[7].id)});
  const qualityForm=document.querySelector<HTMLFormElement>('#quality-form');const updateQuality=()=>{if(!qualityForm)return;const data=new FormData(qualityForm),length=Number(data.get('length')),result=linkQuality(length,Number(data.get('pairs')),data.has('power'));document.querySelector('#length-value')!.textContent=`${length} м`;document.querySelector<HTMLElement>('.quality-meter i')!.style.width=`${result.score}%`;document.querySelector('#quality-result')!.textContent=`${result.score}/100 · ${result.state}`};qualityForm?.addEventListener('input',updateQuality);
  document.querySelectorAll<HTMLButtonElement>('[data-fault]').forEach(button=>button.onclick=()=>{const ok=button.dataset.fault==='cable';document.querySelector('#fault-result')!.textContent=ok?'✓ Верно. Механическое повреждение может вывести из работы пары и снизить согласованную скорость.':'✕ Это не объясняет физический симптом. Сначала исследуйте зажатый кабель.';recordAnswer(SID,'диагностика',ok);if(ok)completeStep(SID,items[10].id)});
  document.querySelectorAll<HTMLElement>('[data-physical-quiz]').forEach(q=>q.querySelector('.check-physical-answer')?.addEventListener('click',()=>{const selected=q.querySelector<HTMLInputElement>('input:checked'),feedback=q.querySelector('.feedback')!;if(!selected){feedback.textContent='⚠ Выберите ответ.';return}const ok=Number(selected.value)===Number(q.dataset.correct);feedback.textContent=ok?'✓ Правильно.':'✕ Ошибка. Вернитесь к объяснению выше.';recordAnswer(SID,q.dataset.topic!,ok);if(ok){const current=items.find(x=>location.hash.endsWith(x.route));if(current)completeStep(SID,current.id)}}));
  document.querySelector<HTMLFormElement>('#control-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);let score=0;controlQuestions.forEach((q,i)=>{if(Number(data.get(`pcq${i}`))===q[2])score++});const percent=score*10;recordAttempt(SID,percent);completeStep(SID,items[11].id);document.querySelector('#control-result')!.innerHTML=`<b>${score}/10 · ${percent}%</b><p>${percent>=80?'Отличный результат.':'Повторите среды передачи, индикацию и порядок диагностики.'}</p>`});
}
