import {ipv4ToInt,prefixMask} from './ipv4Network.ts';
export const intToIpv4=(value:number)=>[24,16,8,0].map(shift=>(value>>>shift)&255).join('.');
export const prefixToMask=(prefix:number)=>intToIpv4(prefixMask(prefix));
export const toBinary=(ip:string)=>ip.split('.').map(x=>Number(x).toString(2).padStart(8,'0')).join('.');
export function subnetInfo(ip:string,prefix:number){const value=ipv4ToInt(ip),mask=prefixMask(prefix),network=(value&mask)>>>0,wildcard=(~mask)>>>0,broadcast=(network|wildcard)>>>0,total=2**(32-prefix),usable=prefix<=30?Math.max(0,total-2):0;return{network:intToIpv4(network),broadcast:intToIpv4(broadcast),first:usable?intToIpv4(network+1):'—',last:usable?intToIpv4(broadcast-1):'—',mask:intToIpv4(mask),total,usable}}
export const inSubnet=(ip:string,network:string,prefix:number)=>subnetInfo(ip,prefix).network===subnetInfo(network,prefix).network;
export function prefixForHosts(hosts:number){if(!Number.isInteger(hosts)||hosts<1)throw new Error('Некорректное число узлов');for(let hostBits=2;hostBits<=32;hostBits++)if(2**hostBits-2>=hosts)return 32-hostBits;throw new Error('Слишком много узлов')}
export function splitSubnet(network:string,prefix:number,newPrefix:number){if(newPrefix<prefix||newPrefix>30)throw new Error('Некорректный новый префикс');const base=ipv4ToInt(subnetInfo(network,prefix).network),size=2**(32-newPrefix),count=2**(newPrefix-prefix);return Array.from({length:count},(_,i)=>`${intToIpv4(base+i*size)}/${newPrefix}`)}
export function allocateVlsm(network:string,prefix:number,requirements:number[]){let cursor=ipv4ToInt(subnetInfo(network,prefix).network);const end=ipv4ToInt(subnetInfo(network,prefix).broadcast);return[...requirements].sort((a,b)=>b-a).map(hosts=>{const p=prefixForHosts(hosts),size=2**(32-p);cursor=Math.ceil(cursor/size)*size;if(cursor+size-1>end)throw new Error('Адресного пространства недостаточно');const result={hosts,prefix:p,network:intToIpv4(cursor),range:subnetInfo(intToIpv4(cursor),p)};cursor+=size;return result})}
